language: python

python:
  - 2.7
# Python 3 support will have to wait, various issues python and model mommy
#  - 3.2
#  - 3.3

env:
  - DJANGO=Django==1.4.15
  - DJANGO=Django==1.5.10
  - DJANGO=Django==1.6.7
  - DJANGO=Django==1.7

matrix:
  exclude:
    - python: 3.2
      env: DJANGO=Django==1.4.15
    - python: 3.3
      env: DJANGO=Django==1.4.15
    - python: 2.6
      env: DJANGO=Django==1.7

install:
  - pip install -q $DJANGO
  - pip install model_mommy
  - pip install coveralls
  - python setup.py -q install

before_script:
  - rm -rf build

script:
  - coverage run manage.py test -v 2 webhooks

after_success:
  - coveralls --verbose
